-- U2 E21
CREATE OR REPLACE FUNCTION FU_HALLAR_ESCALA_SALARIAL(
  FI_SALARIO IN EMPLOYEE.SALARY%TYPE
)
RETURN SALARY_GRADE.GRADE_ID%TYPE AS
  V_SALARY_GRADE_ID SALARY_GRADE.GRADE_ID%TYPE;
BEGIN
  SELECT GRADE_ID
  INTO V_SALARY_GRADE_ID
  FROM SALARY_GRADE
  WHERE FI_SALARIO BETWEEN LOWER_BOUND AND UPPER_BOUND;

  RETURN V_SALARY_GRADE_ID;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20001, 'El salario no coincide con ninguna escala salarial');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002, 'Error al buscar la escala salarial: ' || SQLERRM);
END;

CREATE OR REPLACE PROCEDURE PR_LISTAR_EMPLEADOS(
  PI_ESCALA_SALARIAL IN SALARY_GRADE.GRADE_ID%TYPE
) AS 
  CURSOR C_EMPLEADO IS
    SELECT 
      E.FIRST_NAME AS FIRST_NAME, 
      E.LAST_NAME AS LAST_NAME,
      D.NAME AS DEPARTMENT_NAME,
      J.FUNCTION AS FUNCTION,
      E.SALARY AS SALARY
    FROM EMPLOYEE E, DEPARTMENT D, JOB J
    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.JOB_ID = J.JOB_ID
    AND FU_HALLAR_ESCALA_SALARIAL(E.SALARY) = PI_ESCALA_SALARIAL;
  V_CONTADOR INTEGER := 0;
  R_EMPLEADO C_EMPLEADO%ROWTYPE;
  -- Excepciones
  E_ESCALA_NOT_FOUND EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_ESCALA_NOT_FOUND, -20001);
  E_EMPLEADOS_NOT_FOUND EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_EMPLEADOS_NOT_FOUND, -20003);
BEGIN
  -- Validar que exista la escala
  DECLARE
    V_SALARY_GRADE_ID SALARY_GRADE.GRADE_ID%TYPE;
  BEGIN
    SELECT GRADE_ID
    INTO V_SALARY_GRADE_ID
    FROM SALARY_GRADE
    WHERE GRADE_ID = PI_ESCALA_SALARIAL;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE E_ESCALA_NOT_FOUND;
  END;

  -- Iterar sobre los empleados
  FOR R_EMPLEADO IN C_EMPLEADO LOOP
    V_CONTADOR := V_CONTADOR + 1;
    DBMS_OUTPUT.PUT_LINE('------ Empleado n°' || V_CONTADOR);
    DBMS_OUTPUT.PUT_LINE('Nombre: ' || R_EMPLEADO.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('Apellido: ' || R_EMPLEADO.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE('Departamento: ' || R_EMPLEADO.DEPARTMENT_NAME);
    DBMS_OUTPUT.PUT_LINE('Tarea: ' || R_EMPLEADO.FUNCTION);
    DBMS_OUTPUT.PUT_LINE('Salario: ' || R_EMPLEADO.SALARY);
  END LOOP;

  -- Validar que haya encontrado empleados
  IF V_CONTADOR = 0 THEN
    RAISE E_EMPLEADOS_NOT_FOUND;
  END IF;

  -- Imprimir total
  DBMS_OUTPUT.PUT_LINE('------');
  DBMS_OUTPUT.PUT_LINE('Total empleados: ' || V_CONTADOR);
EXCEPTION
  WHEN E_ESCALA_NOT_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Escala salarial no encontrada.');
  WHEN E_EMPLEADOS_NOT_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontraron empleados para la escala salarial.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;
