CREATE OR REPLACE PROCEDURE PR_LISTADO_DEPT_EMPL(
  PI_LOCATION_ID LOCATION.LOCATION_ID%TYPE
) AS
  -- Variables
  V_REGIONAL_GROUP LOCATION.REGIONAL_GROUP%TYPE;
  V_CONTADOR INTEGER := 0;
  -- Cursores
  CURSOR C_DEPTOS IS (
    SELECT 
      D.DEPARTMENT_ID AS ID, 
      D.NAME AS NAME,
      COUNT(E.EMPLOYEE_ID) AS TOTAL_EMPLEADOS
    FROM DEPARTMENT D LEFT OUTER JOIN EMPLOYEE E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    WHERE D.LOCATION_ID = PI_LOCATION_ID
    GROUP BY ID, NAME
  );
  CURSOR C_EMPLEADOS (P_DEP_ID DEPARTMENT.DEPARTMENT_ID%TYPE) IS 
    SELECT 
      EMPLOYEE_ID,
      FIRST_NAME,
      LAST_NAME
    FROM EMPLOYEE
    WHERE DEPARTMENT_ID = P_DEP_ID
    ORDER BY LAST_NAME, FIRST_NAME;
BEGIN
  SELECT REGIONAL_GROUP
  INTO V_REGIONAL_GROUP
  FROM LOCATION
  WHERE LOCATION_ID = PI_LOCATION_ID;

  DBMS_OUTPUT.PUT_LINE('Localidad: ' || V_REGIONAL_GROUP);

  FOR R_DEPTOS IN C_DEPTOS LOOP
    V_CONTADOR := V_CONTADOR + 1;

    DBMS_OUTPUT.PUT_LINE('----------------');

    IF R_DEPTOS.TOTAL_EMPLEADOS = 0 THEN
      DBMS_OUTPUT.PUT_LINE('No se encontraron empleados en el Depto.: ' || R_DEPTOS.ID);
      DBMS_OUTPUT.PUT_LINE('');
      CONTINUE;
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('Departamento ' || V_CONTADOR || ' - ' || R_DEPTOS.NAME);
    DBMS_OUTPUT.PUT_LINE('Emp_id        Nombre        Apellido');
    FOR R_EMPLEADO IN C_EMPLEADOS(R_DEPTOS.ID) LOOP
      DBMS_OUTPUT.PUT_LINE(R_EMPLEADO.EMPLOYEE_ID || '        ' || R_EMPLEADO.FIRST_NAME || '        ' || R_EMPLEADO.LAST_NAME);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Total empleados: ' || R_DEPTOS.TOTAL_EMPLEADOS);
    DBMS_OUTPUT.PUT_LINE('');
  END LOOP;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontro registro para el LOCATION_ID: ' || PI_LOCATION_iD);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END PR_LISTADO_DEPT_EMPL;
