-- U2 E06
CREATE OR REPLACE PROCEDURE PR_ALTA (
  PI_NOMBRE IN DEPARTMENT.NAME%TYPE,
  PI_LOCATION_ID IN DEPARTMENT.LOCATION_ID%TYPE,
  PO_DEP_ID OUT DEPARTMENT.DEPARTMENT_ID%TYPE
) AS
  V_ULTIMO_DEP_ID DEPARTMENT.DEPARTMENT_ID%TYPE;
  E_INVALID_LOCATION EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_INVALID_LOCATION, -02291);
BEGIN
  SELECT MAX(DEPARTMENT_ID) 
  INTO V_ULTIMO_DEP_ID
  FROM DEPARTMENT;

  PO_DEP_ID := V_ULTIMO_DEP_ID + 1;

  INSERT INTO DEPARTMENT (DEPARTMENT_ID, NAME, LOCATION_ID)
  VALUES (
    PO_DEP_ID,
    PI_NOMBRE,
    PI_LOCATION_ID
  );
EXCEPTION 
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontraron departamentos');
  WHEN E_INVALID_LOCATION THEN
    DBMS_OUTPUT.PUT_LINE('No existe registro para ese LOCATION_ID');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END PR_ALTA;

DECLARE
  V_DEP_ID DEPARTMENT.DEPARTMENT_ID%TYPE;
BEGIN
  PR_ALTA(
    '&INGRESE_NOMBRE_DEPTO', 
    &INGRESE_LOCATION_ID,
    V_DEP_ID
  );

  DBMS_OUTPUT.PUT_LINE('Nuevo ID de depto.: ' || V_DEP_ID);
END;
