-- 1)
CREATE OR REPLACE PROCEDURE PR_ALTA_JOB (
  PI_JOB_FUNCTION JOB.FUNCTION%TYPE
) AS
  V_JOB_ID JOB.JOB_ID%TYPE;
BEGIN
  SELECT MAX(JOB_ID)
  INTO V_JOB_ID
  FROM JOB;
  
  V_JOB_ID := V_JOB_ID + 1;

  INSERT INTO JOB (JOB_ID, FUNCTION)
  VALUES (V_JOB_ID, UPPER(PI_JOB_FUNCTION));
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END PR_ALTA_JOB;

-- 2)
CREATE OR REPLACE PROCEDURE PR_UPDATE_JOB (
  PI_JOB_ID JOB.JOB_ID%TYPE,
  PI_JOB_FUNCTION JOB.FUNCTION%TYPE
) AS
  E_NOT_FOUND EXCEPTION;
BEGIN
  UPDATE JOB
  SET FUNCTION = PI_JOB_FUNCTION
  WHERE JOB_ID = PI_JOB_ID;

  IF SQL%ROWCOUNT = 0 THEN
    RAISE E_NOT_FOUND;
  END IF;
EXCEPTION
  WHEN E_NOT_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el job con ID: ' || PI_JOB_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 3)
CREATE OR REPLACE PROCEDURE PR_LISTA_EMP (
  PI_DEPARTMENT_ID DEPARTMENT.DEPARTMENT_ID%TYPE
) AS
  CURSOR C_EMPLEADOS IS 
    SELECT FIRST_NAME, LAST_NAME
    FROM EMPLOYEE
    WHERE DEPARTMENT_ID = PI_DEPARTMENT_ID
    ;
  V_CONT INTEGER := 0;
  V_CANT_EMPLEADOS INTEGER := 0;
  E_SIN_EMPLEADOS EXCEPTION;
  E_DEPTO_INEXISTENTE EXCEPTION;
BEGIN
  DECLARE
    V_DEPTO_ID DEPARTMENT.DEPARTMENT_ID%TYPE := PI_DEPARTMENT_ID;
  BEGIN
    SELECT DEPARTMENT_ID
    INTO V_DEPTO_ID
    FROM DEPARTMENT
    WHERE DEPARTMENT_ID = V_DEPTO_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE E_DEPTO_INEXISTENTE;
  END;
  
  SELECT COUNT(*)
  INTO V_CANT_EMPLEADOS
  FROM EMPLOYEE
  WHERE DEPARTMENT_ID = PI_DEPARTMENT_ID;

  IF V_CANT_EMPLEADOS = 0 THEN
    RAISE E_SIN_EMPLEADOS;
  END IF;

  FOR REC IN C_EMPLEADOS LOOP
    V_CONT := V_CONT + 1;
    DBMS_OUTPUT.PUT_LINE(REC.LAST_NAME || ', ' || REC.FIRST_NAME);
  END LOOP;
EXCEPTION
  WHEN E_SIN_EMPLEADOS THEN
    DBMS_OUTPUT.PUT_LINE('El departamento no tiene empleados');
  WHEN E_DEPTO_INEXISTENTE THEN
    DBMS_OUTPUT.PUT_LINE('El departamento no existe');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 4)
CREATE OR REPLACE PROCEDURE PR_CONSULTA_PRECIO (
  PI_PRODUCT_ID IN PRODUCT.PRODUCT_ID%TYPE,
  PO_LIST_PRICE OUT PRICE.LIST_PRICE%TYPE,
  PO_MIN_PRICE OUT PRICE.MIN_PRICE%TYPE
) AS
BEGIN
  SELECT LIST_PRICE, MIN_PRICE
  INTO PO_LIST_PRICE, PO_MIN_PRICE
  FROM PRICE
  WHERE PRODUCT_ID = PI_PRODUCT_ID
  AND END_DATE IS NULL;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el producto con ID: ' || PI_PRODUCT_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 5)
CREATE OR REPLACE FUNCTION FU_Q_CREDIT (
  PI_CUSTOMER_ID IN CUSTOMER.CUSTOMER_ID%TYPE
) RETURN CUSTOMER.CREDIT_LIMIT%TYPE AS
  V_CREDIT_LIMIT CUSTOMER.CREDIT_LIMIT%TYPE;
BEGIN
  SELECT CREDIT_LIMIT
  INTO V_CREDIT_LIMIT
  FROM CUSTOMER
  WHERE CUSTOMER_ID = PI_CUSTOMER_ID;
  RETURN V_CREDIT_LIMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
END;

-- 6)
CREATE OR REPLACE FUNCTION FU_VALIDA_LOC (
  PI_LOCATION_ID LOCATION.LOCATION_ID%TYPE
) RETURN BOOLEAN AS
  V_LOC_ID LOCATION.LOCATION_ID%TYPE;
BEGIN
  SELECT LOCATION_ID
  INTO V_LOC_ID
  FROM LOCATION
  WHERE LOCATION_ID = PI_LOCATION_ID;

  RETURN TRUE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN FALSE;
END;

-- 7)
CREATE OR REPLACE PROCEDURE PR_NEW_DEPT (
  PI_DEPARTMENT_ID IN DEPARTMENT.DEPARTMENT_ID%TYPE,
  PI_DEPARTMENT_NAME IN DEPARTMENT.NAME%TYPE,
  PI_LOCATION_ID IN DEPARTMENT.LOCATION_ID%TYPE
) AS
  E_LOCATION_NOT_FOUND EXCEPTION;
  E_DEPARTMENT_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_DEPARTMENT_EXISTS, -00001);
BEGIN
  IF NOT FU_VALIDA_LOC(PI_LOCATION_ID) THEN
    RAISE E_LOCATION_NOT_FOUND;
  END IF;

  INSERT INTO DEPARTMENT (DEPARTMENT_ID, NAME, LOCATION_ID)
  VALUES (PI_DEPARTMENT_ID, PI_DEPARTMENT_NAME, PI_LOCATION_ID);
EXCEPTION
  WHEN E_LOCATION_NOT_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No existe la location ID: ' || PI_LOCATION_ID);
  WHEN E_DEPARTMENT_EXISTS THEN
    DBMS_OUTPUT.PUT_LINE('Ya existe un departamento con ID: ' || PI_DEPARTMENT_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 8)
CREATE OR REPLACE FUNCTION FU_IVA (
  FI_VALOR IN NUMBER
) RETURN NUMBER AS
  V_IVA CONSTANT NUMBER(3,2) := 1.21;
BEGIN
  RETURN FI_VALOR * V_IVA;
END;
