-- 1)
DECLARE
  V_VAR NUMBER(8,3);
  V_A/*, V_B*/ NUMBER;
  V_FEC_INGRESO DATE := SYSDATE + 2;
--  V_NOMBRE VARCHAR2(30) NOT NULL;
  V_LOGICO BOOLEAN DEFAULT to_boolean('TRUE');
BEGIN
  DBMS_OUTPUT.PUT_LINE('Compila');
  DBMS_OUTPUT.PUT_LINE('Fecha: ' || V_FEC_INGRESO);
END;

-- 2)
DECLARE
  V_USERNAME VARCHAR2(100) := '&INGRESE_USUARIO';
  V_FECHA DATE := SYSDATE;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hola, soy ' || V_USERNAME);
  DBMS_OUTPUT.PUT_LINE('Hoy es: ' || V_FECHA);
END;

-- 3)
DECLARE
  V_EMPLEADO EMPLOYEE.EMPLOYEE_ID%TYPE := &INGRESE_ID;
  TYPE TR_EMP IS RECORD (
    NOMBRE EMPLOYEE.FIRST_NAME%TYPE,
    APELLIDO EMPLOYEE.LAST_NAME%TYPE,
    SALARIO EMPLOYEE.SALARY%TYPE
  );
  R_EMP TR_EMP;
BEGIN
  SELECT FIRST_NAME, LAST_NAME, SALARY
  INTO R_EMP
  FROM EMPLOYEE
  WHERE EMPLOYEE_ID = V_EMPLEADO;
  DBMS_OUTPUT.PUT_LINE(R_EMP.NOMBRE || ', ' || R_EMP.APELLIDO || ' tiene un salario de ' || R_EMP.SALARIO || ' pesos.');
END;

-- 4)
DECLARE
  V_ORDEN_ID SALES_ORDER.ORDER_ID%TYPE := &INGRESE_ORDER_ID;
  TYPE TR_ORDER IS RECORD (
    ORDER_ID SALES_ORDER.ORDER_ID%TYPE,
    ORDER_DATE SALES_ORDER.ORDER_DATE%TYPE,
    CUSTOMER_ID SALES_ORDER.CUSTOMER_ID%TYPE,
    SHIP_DATE SALES_ORDER.SHIP_DATE%TYPE,
    TOTAL SALES_ORDER.TOTAL%TYPE
  );
  R_ORDER TR_ORDER;
BEGIN
  SELECT ORDER_ID, ORDER_DATE, CUSTOMER_ID, SHIP_DATE, TOTAL
  INTO R_ORDER
  FROM SALES_ORDER
  WHERE ORDER_ID = V_ORDEN_ID;

  DBMS_OUTPUT.PUT_LINE('ID: ' || R_ORDER.ORDER_ID);
  DBMS_OUTPUT.PUT_LINE('Fecha: ' || R_ORDER.ORDER_DATE);
  DBMS_OUTPUT.PUT_LINE('Customer ID: ' || R_ORDER.CUSTOMER_ID);
  DBMS_OUTPUT.PUT_LINE('Ship date: ' || R_ORDER.SHIP_DATE);
  DBMS_OUTPUT.PUT_LINE('Total: ' || R_ORDER.TOTAL);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontro el ID: ' || V_ORDEN_ID);
END;

-- 5)
DECLARE
  V_ID_CLIENTE CUSTOMER.CUSTOMER_ID%TYPE := &INGRESE_SU_ID;
  V_CANT_ORDENES INTEGER := 0;
  V_CUSTOMER_NAME CUSTOMER.NAME%TYPE;
BEGIN
  SELECT COUNT(ORDER_ID)
  INTO V_CANT_ORDENES
  FROM SALES_ORDER
  WHERE CUSTOMER_ID = V_ID_CLIENTE;

  SELECT NAME
  INTO V_CUSTOMER_NAME
  FROM CUSTOMER
  WHERE CUSTOMER_ID = V_ID_CLIENTE;

  CASE 
    WHEN V_CANT_ORDENES < 3 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES REGULAR');
    WHEN V_CANT_ORDENES BETWEEN 4 AND 6 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES BUENO');
    ELSE
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES MUY BUENO');
  END CASE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontraron órdenes sujetas al ID de cliente');
END;

-- 6)
DECLARE
  V_DEPTO_ID DEPARTMENT.DEPARTMENT_ID%TYPE := &INGRESE_ID_DEPTO;
  V_NOMBRE_DEPTO DEPARTMENT.NAME%TYPE;
  V_CANT_EMPLEADOS INTEGER;
BEGIN
  SELECT D.NAME, COUNT(E.EMPLOYEE_ID)
  INTO V_NOMBRE_DEPTO, V_CANT_EMPLEADOS
  FROM DEPARTMENT D
  LEFT OUTER JOIN EMPLOYEE E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
  WHERE D.DEPARTMENT_ID = V_DEPTO_ID
  GROUP BY D.NAME;

  DBMS_OUTPUT.PUT_LINE('Departamento: ' || V_NOMBRE_DEPTO);
  CASE
    WHEN V_CANT_EMPLEADOS = 0 THEN
      DBMS_OUTPUT.PUT_LINE('Sin empleados');
    WHEN V_CANT_EMPLEADOS BETWEEN 1 AND 10 THEN
      DBMS_OUTPUT.PUT_LINE('Normal');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Muchos');
  END CASE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el departamento con ID: ' || V_DEPTO_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 7)
DECLARE
  V_PRODUCT_ID PRODUCT.PRODUCT_ID%TYPE := &INGRESE_PRODUCT_ID;
  V_DESCRIPCION PRODUCT.DESCRIPTION%TYPE;
  V_CANT_VENTAS INTEGER;
BEGIN
  SELECT P.DESCRIPTION, COUNT(I.ORDER_ID)
  INTO V_DESCRIPCION, V_CANT_VENTAS
  FROM PRODUCT P
  LEFT OUTER JOIN ITEM I
    ON P.PRODUCT_ID = I.PRODUCT_ID
  WHERE P.PRODUCT_ID = V_PRODUCT_ID
  GROUP BY (P.DESCRIPTION);

  DBMS_OUTPUT.PUT_LINE('Producto: ' || V_DESCRIPCION);
  DBMS_OUTPUT.PUT_LINE('Ventas: ' || V_CANT_VENTAS);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el producto con ID: ' || V_PRODUCT_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 8)
DECLARE
  V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &INGRESE_ID_EMPLEADO;
  TYPE TR_EMPLEADO IS RECORD (
    EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE,
    EMPLOYEE_NAME VARCHAR2(250),
    MANAGER_ID EMPLOYEE.MANAGER_ID%TYPE,
    MANAGER_NAME VARCHAR2(250)
  );
  R_EMPLEADO TR_EMPLEADO;
BEGIN
  SELECT E1.EMPLOYEE_ID, 
    E1.FIRST_NAME || ' ' || E1.LAST_NAME,
    E1.MANAGER_ID,
    E2.FIRST_NAME || ' ' || E2.LAST_NAME
  INTO R_EMPLEADO
  FROM EMPLOYEE E1
  LEFT OUTER JOIN EMPLOYEE E2
    ON E1.MANAGER_ID = E2.EMPLOYEE_ID
  WHERE E1.EMPLOYEE_ID = V_EMPLOYEE_ID;

  DBMS_OUTPUT.PUT_LINE('ID: ' || R_EMPLEADO.EMPLOYEE_ID);
  DBMS_OUTPUT.PUT_LINE('Nombre: ' || R_EMPLEADO.EMPLOYEE_NAME);
  IF R_EMPLEADO.MANAGER_ID IS NOT NULL THEN
    DBMS_OUTPUT.PUT_LINE('ID Jefe: ' || R_EMPLEADO.MANAGER_ID);
    DBMS_OUTPUT.PUT_LINE('Nombre Jefe: ' || R_EMPLEADO.MANAGER_NAME);
  ELSE
    DBMS_OUTPUT.PUT_LINE('Jefe: No tiene');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el empleado con ID: ' || V_EMPLOYEE_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 9)
DECLARE
  V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &INGRESE_ID_EMPLEADO;
  V_RESULTADO INTEGER;
  V_MENSAJE VARCHAR2(100) := '';
  TYPE TR_EMPLEADO IS RECORD (
    APELLIDO EMPLOYEE.LAST_NAME%TYPE,
    NOMBRE EMPLOYEE.FIRST_NAME%TYPE,
    SALARIO EMPLOYEE.SALARY%TYPE
  );
  R_EMPLEADO TR_EMPLEADO;
BEGIN
  SELECT LAST_NAME, FIRST_NAME, SALARY
  INTO R_EMPLEADO
  FROM EMPLOYEE
  WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;

  DBMS_OUTPUT.PUT_LINE(R_EMPLEADO.APELLIDO || ', ' || R_EMPLEADO.NOMBRE);
  V_RESULTADO := FLOOR(R_EMPLEADO.SALARIO / 100);
  FOR I IN 1..V_RESULTADO LOOP
    V_MENSAJE := V_MENSAJE || '*';
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró empleado para el ID: ' || V_EMPLOYEE_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 10)
DECLARE
  V_NUM_MULTIPLOS INTEGER := &INGRESE_NUMERO;
  V_MENSAJE VARCHAR2(100) := '';
  E_NUMERO_GRANDE EXCEPTION;
BEGIN
  IF V_NUM_MULTIPLOS > 10 THEN
    RAISE E_NUMERO_GRANDE;
  END IF;
  FOR I IN 1..V_NUM_MULTIPLOS LOOP
    IF I = V_NUM_MULTIPLOS THEN
      V_MENSAJE := V_MENSAJE || 3 * I;
      CONTINUE;
    END IF;
    V_MENSAJE := V_MENSAJE || 3 * I || ', ';
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Resultado: ' || V_MENSAJE);
EXCEPTION
  WHEN E_NUMERO_GRANDE THEN
    DBMS_OUTPUT.PUT_LINE('No se admiten más de 10 múltiplos.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;
