-- 1)
DECLARE
  V_VAR NUMBER(8,3);
  V_A/*, V_B*/ NUMBER;
  V_FEC_INGRESO DATE := SYSDATE + 2;
--  V_NOMBRE VARCHAR2(30) NOT NULL;
  V_LOGICO BOOLEAN DEFAULT to_boolean('TRUE');
BEGIN
  DBMS_OUTPUT.PUT_LINE('Compila');
  DBMS_OUTPUT.PUT_LINE('Fecha: ' || V_FEC_INGRESO);
END;

-- 2)
DECLARE
  V_USERNAME VARCHAR2(100) := '&INGRESE_USUARIO';
  V_FECHA DATE := SYSDATE;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hola, soy ' || V_USERNAME);
  DBMS_OUTPUT.PUT_LINE('Hoy es: ' || V_FECHA);
END;

-- 3)
DECLARE
  V_EMPLEADO EMPLOYEE.EMPLOYEE_ID%TYPE := &INGRESE_ID;
  TYPE TR_EMP IS RECORD (
    NOMBRE EMPLOYEE.FIRST_NAME%TYPE,
    APELLIDO EMPLOYEE.LAST_NAME%TYPE,
    SALARIO EMPLOYEE.SALARY%TYPE
  );
  R_EMP TR_EMP;
BEGIN
  SELECT FIRST_NAME, LAST_NAME, SALARY
  INTO R_EMP
  FROM EMPLOYEE
  WHERE EMPLOYEE_ID = V_EMPLEADO;
  DBMS_OUTPUT.PUT_LINE(R_EMP.NOMBRE || ', ' || R_EMP.APELLIDO || ' tiene un salario de ' || R_EMP.SALARIO || ' pesos.');
END;

-- 4)
DECLARE
  V_ORDEN_ID SALES_ORDER.ORDER_ID%TYPE := &INGRESE_ORDER_ID;
  TYPE TR_ORDER IS RECORD (
    ORDER_ID SALES_ORDER.ORDER_ID%TYPE,
    ORDER_DATE SALES_ORDER.ORDER_DATE%TYPE,
    CUSTOMER_ID SALES_ORDER.CUSTOMER_ID%TYPE,
    SHIP_DATE SALES_ORDER.SHIP_DATE%TYPE,
    TOTAL SALES_ORDER.TOTAL%TYPE
  );
  R_ORDER TR_ORDER;
BEGIN
  SELECT ORDER_ID, ORDER_DATE, CUSTOMER_ID, SHIP_DATE, TOTAL
  INTO R_ORDER
  FROM SALES_ORDER
  WHERE ORDER_ID = V_ORDEN_ID;

  DBMS_OUTPUT.PUT_LINE('ID: ' || R_ORDER.ORDER_ID);
  DBMS_OUTPUT.PUT_LINE('Fecha: ' || R_ORDER.ORDER_DATE);
  DBMS_OUTPUT.PUT_LINE('Customer ID: ' || R_ORDER.CUSTOMER_ID);
  DBMS_OUTPUT.PUT_LINE('Ship date: ' || R_ORDER.SHIP_DATE);
  DBMS_OUTPUT.PUT_LINE('Total: ' || R_ORDER.TOTAL);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontro el ID: ' || V_ORDEN_ID);
END;

-- 5)
DECLARE
  V_ID_CLIENTE CUSTOMER.CUSTOMER_ID%TYPE := &INGRESE_SU_ID;
  V_CANT_ORDENES INTEGER := 0;
  V_CUSTOMER_NAME CUSTOMER.NAME%TYPE;
BEGIN
  SELECT COUNT(ORDER_ID)
  INTO V_CANT_ORDENES
  FROM SALES_ORDER
  WHERE CUSTOMER_ID = V_ID_CLIENTE;

  SELECT NAME
  INTO V_CUSTOMER_NAME
  FROM CUSTOMER
  WHERE CUSTOMER_ID = V_ID_CLIENTE;

  CASE 
    WHEN V_CANT_ORDENES < 3 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES REGULAR');
    WHEN V_CANT_ORDENES BETWEEN 4 AND 6 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES BUENO');
    ELSE
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES MUY BUENO');
  END CASE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontraron órdenes sujetas al ID de cliente');
END;
