SELECT *
FROM EMPLOYEE;

-- NVL(column, value) nos permite reemplazar valores nulos por otros
SELECT NVL(commission, 0)
FROM EMPLOYEE;

-- Variables se definen con : o &
-- Ejemplo:
-- SELECT * FROM EMPLOYEE WHERE employee_id = :emp_id;


SELECT E.FIRST_NAME, E.LAST_NAME, D.NAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;


SELECT * FROM SALES_ORDER
WHERE ORDER_DATE >= TO_DATE('2010-01-01', 'YYYY-MM-DD');

SELECT SYSDATE FROM DUAL;
-- resta 1 dia
SELECT SYSDATE-1 FROM DUAL;
SELECT  TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') FECHA,
        TO_CHAR(TRUNC(SYSDATE), 'DD/MM/YYYY HH24:MI:SS') FECHA_TRUNC,
        ROUND(124.742, 1) REDONDEO,
        INITCAP('hola mundo') INICIAL_MAYUSCULA
FROM DUAL;

SELECT DEPARTMENT_ID, COUNT(1)
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
HAVING COUNT(1) > 1;

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM EMPLOYEE E
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

-- Parcial 14 de septiembre
-- 2do parcial 2 de noviembre
-- Recuperatorio 9 de noviembre
-- Recuperatorio fuera de cursada 16 de noviembre

SELECT E1.FIRST_NAME || ' ' || E1.LAST_NAME AS FULL_NAME, E1.SALARY, D.NAME AS DEPARTMENT_NAME, J.FUNCTION
FROM EMPLOYEE E1, DEPARTMENT D, JOB J
WHERE E1.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E1.JOB_ID = J.JOB_ID
  AND E1.SALARY > (SELECT E2.SALARY FROM EMPLOYEE E2 WHERE E2.EMPLOYEE_ID = E1.MANAGER_ID);


SELECT E1.FIRST_NAME || ' ' || E1.LAST_NAME AS FULL_NAME, E1.SALARY, D.NAME AS DEPARTMENT_NAME, J.FUNCTION, E3.FIRST_NAME || ' ' || E3.LAST_NAME AS MANAGER_NAME
FROM EMPLOYEE E1, DEPARTMENT D, JOB J, EMPLOYEE E3
WHERE E1.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E1.JOB_ID = J.JOB_ID
  AND E1.MANAGER_ID = E3.EMPLOYEE_ID
  AND E1.SALARY > (SELECT E2.SALARY FROM EMPLOYEE E2 WHERE E2.EMPLOYEE_ID = E1.MANAGER_ID);

/*

SELECT CAMPO1, CAMPO2
INTO VARIABLE 1, VARIABLE2
FROM TABLA
WHERE CONDICION

SELECT INTO tiene que devolver 1 sola linea o da error
*/
