-- 1)
INSERT INTO JOB (JOB_ID, FUNCTION)
VALUES (673, 'CPO'),
  (674, 'CIO'),
  (675, 'CFO');

-- 2)
COMMIT;

-- 3)
DELETE FROM JOB WHERE JOB_ID IN (673, 674, 675);

-- 4)
ROLLBACK;

-- 5)
SELECT * FROM JOB;

-- 6)
UPDATE CUSTOMER
SET NAME = 'JOCKYSPORTS'
WHERE CUSTOMER_ID = 100;

-- 7)
savepoint A;

-- 8)
UPDATE CUSTOMER
SET NAME = 'TKB SPORTS'
WHERE CUSTOMER_ID = 101;

-- 9)
SAVEPOINT B;

-- 10)
ROLLBACK TO A;

-- 11)
SELECT * FROM CUSTOMER;

-- 12)
COMMIT;

-- 13)
DELETE FROM DEPARTMENT
WHERE DEPARTMENT_ID = 10;
-- No se puede eliminar porque hay FK que lo referencian

-- 14)
INSERT INTO DEPARTMENT (DEPARTMENT_ID, NAME, LOCATION_ID)
VALUES (50, 'EDUCATION', 100);
-- No se puede porque no existe la location 100

-- 15)
INSERT INTO DEPARTMENT (DEPARTMENT_ID, NAME)
VALUES (43, 'OPERATIONS');
-- No se puede porque el departamento con ID 43 ya existe

-- 16)
UPDATE DEPARTMENT
SET LOCATION_ID = 155
WHERE DEPARTMENT_ID = 20;
-- No existe LOCATION_ID = 155

-- 17)
UPDATE EMPLOYEE
SET SALARY = SALARY * 1.10
WHERE SALARY < (SELECT AVG(E1.SALARY) FROM EMPLOYEE E1);

-- 18)
UPDATE CUSTOMER C
SET CREDIT_LIMIT = CREDIT_LIMIT * 1.05
WHERE EXISTS (
    SELECT 1
    FROM SALES_ORDER S
    WHERE S.CUSTOMER_ID = C.CUSTOMER_ID
    HAVING COUNT(S.ORDER_ID) > 5
  );

-- 19)
ROLLBACK;
