-- 1)
SELECT * FROM EMPLOYEE;
SELECT * FROM JOB;
SELECT * FROM SALARY_GRADE;
SELECT * FROM CUSTOMER;
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, J.FUNCTION
FROM EMPLOYEE E, JOB J
WHERE E.JOB_ID = J.JOB_ID;

-- 2)
SELECT FUNCTION FROM JOB;

-- 3)
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME
FROM EMPLOYEE
ORDER BY LAST_NAME;

-- 4)
SELECT LAST_NAME, FIRST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 1500 AND 2850;

-- 5)
SELECT EMPLOYEE_ID, LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME, HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN TO_DATE('01-01-2006', 'DD-MM-YYYY') AND TO_DATE('31-12-2006', 'DD-MM-YYYY');

-- 6)
SELECT DEPARTMENT_ID, NAME
FROM DEPARTMENT
WHERE LOCATION_ID = 122;

-- 7)
SELECT DEPARTMENT_ID, NAME
FROM DEPARTMENT
WHERE LOCATION_ID = &INGRESE_LOCATION_ID;

-- 8)
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME, SALARY
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

-- 9)
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME, NVL(TO_CHAR(COMMISSION), 'Sin Comisión') AS COMMISSION
FROM EMPLOYEE;

-- 10)
SELECT E.LAST_NAME || ', ' || E.FIRST_NAME AS FULL_NAME, E.DEPARTMENT_ID, D.NAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 11)
SELECT E.LAST_NAME || ', ' || E.FIRST_NAME AS FULL_NAME, J.FUNCTION, D.NAME, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E.JOB_ID = J.JOB_ID
ORDER BY E.LAST_NAME;

-- 12)
SELECT 
  E.LAST_NAME || ', ' || E.FIRST_NAME AS FULL_NAME,
  D.NAME,
  L.REGIONAL_GROUP
FROM 
  EMPLOYEE E, 
  DEPARTMENT D,
  LOCATION L
WHERE
  E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
  D.LOCATION_ID = L.LOCATION_ID AND
  E.COMMISSION IS NOT NULL;

-- 13)
SELECT 
  E.EMPLOYEE_ID,
  E.LAST_NAME,
  E.SALARY,
  SG.GRADE_ID
FROM 
  EMPLOYEE E,
  SALARY_GRADE SG
WHERE 
  E.SALARY BETWEEN SG.LOWER_BOUND AND SG.UPPER_BOUND;

-- 14)
SELECT 
  E1.EMPLOYEE_ID AS EMPLOYEE_ID,
  E1.LAST_NAME || ', ' || E1.FIRST_NAME AS EMP_NAME,
  E2.EMPLOYEE_ID AS MANAGER_ID,
  E2.LAST_NAME || ', ' || E2.FIRST_NAME AS MNG_NAME
FROM 
  EMPLOYEE E1,
  EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

-- 15)
SELECT 
  E1.EMPLOYEE_ID AS EMPLOYEE_ID,
  E1.LAST_NAME || ', ' || E1.FIRST_NAME AS EMP_NAME,
  E2.EMPLOYEE_ID AS MANAGER_ID,
  E2.LAST_NAME || ', ' || E2.FIRST_NAME AS MNG_NAME
FROM 
  EMPLOYEE E1 LEFT OUTER JOIN EMPLOYEE E2 
    ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

-- 16)
SELECT SO.ORDER_ID, C.NAME, P.DESCRIPTION
FROM
  SALES_ORDER SO,
  CUSTOMER C,
  ITEM I,
  PRODUCT P
WHERE
  SO.CUSTOMER_ID = C.CUSTOMER_ID AND
  SO.ORDER_ID = I.ORDER_ID AND
  I.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SO.ORDER_ID;

-- 17)
SELECT COUNT(*) FROM CUSTOMER;

-- 18)
SELECT COUNT(*) FROM CUSTOMER C WHERE C.STATE = 'NY';

-- 19)
--SELECT COUNT(*) AS JEFES
--FROM EMPLOYEE MNG, EMPLOYEE EMP
--WHERE MNG.EMPLOYEE_ID = EMP.EMPLOYEE_ID;