-- 1)
SELECT * FROM EMPLOYEE;
SELECT * FROM JOB;
SELECT * FROM SALARY_GRADE;
SELECT * FROM CUSTOMER;
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, J.FUNCTION
FROM EMPLOYEE E, JOB J
WHERE E.JOB_ID = J.JOB_ID;

-- 2)
SELECT FUNCTION FROM JOB;

-- 3)
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME
FROM EMPLOYEE
ORDER BY LAST_NAME;

-- 4)
SELECT LAST_NAME, FIRST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 1500 AND 2850;

-- 5)
SELECT EMPLOYEE_ID, LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME, HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN TO_DATE('01-01-2006', 'DD-MM-YYYY') AND TO_DATE('31-12-2006', 'DD-MM-YYYY');

-- 6)
SELECT DEPARTMENT_ID, NAME
FROM DEPARTMENT
WHERE LOCATION_ID = 122;

-- 7)
SELECT DEPARTMENT_ID, NAME
FROM DEPARTMENT
WHERE LOCATION_ID = &INGRESE_LOCATION_ID;

-- 8)
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME, SALARY
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

-- 9)
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME, NVL(TO_CHAR(COMMISSION), 'Sin Comisión') AS COMMISSION
FROM EMPLOYEE;

-- 10)
SELECT E.LAST_NAME || ', ' || E.FIRST_NAME AS FULL_NAME, E.DEPARTMENT_ID, D.NAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 11)
SELECT E.LAST_NAME || ', ' || E.FIRST_NAME AS FULL_NAME, J.FUNCTION, D.NAME, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E.JOB_ID = J.JOB_ID
ORDER BY E.LAST_NAME;

-- 12)
SELECT 
  E.LAST_NAME || ', ' || E.FIRST_NAME AS FULL_NAME,
  D.NAME,
  L.REGIONAL_GROUP
FROM 
  EMPLOYEE E, 
  DEPARTMENT D,
  LOCATION L
WHERE
  E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
  D.LOCATION_ID = L.LOCATION_ID AND
  E.COMMISSION IS NOT NULL;

-- 13)
SELECT 
  E.EMPLOYEE_ID,
  E.LAST_NAME,
  E.SALARY,
  SG.GRADE_ID
FROM 
  EMPLOYEE E,
  SALARY_GRADE SG
WHERE 
  E.SALARY BETWEEN SG.LOWER_BOUND AND SG.UPPER_BOUND;

-- 14)
SELECT 
  E1.EMPLOYEE_ID AS EMPLOYEE_ID,
  E1.LAST_NAME || ', ' || E1.FIRST_NAME AS EMP_NAME,
  E2.EMPLOYEE_ID AS MANAGER_ID,
  E2.LAST_NAME || ', ' || E2.FIRST_NAME AS MNG_NAME
FROM 
  EMPLOYEE E1,
  EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID;

-- 15)
SELECT 
  E1.EMPLOYEE_ID AS EMPLOYEE_ID,
  E1.LAST_NAME || ', ' || E1.FIRST_NAME AS EMP_NAME,
  E2.EMPLOYEE_ID AS MANAGER_ID,
  E2.LAST_NAME || ', ' || E2.FIRST_NAME AS MNG_NAME
FROM 
  EMPLOYEE E1 LEFT OUTER JOIN EMPLOYEE E2 
    ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

-- 16)
SELECT SO.ORDER_ID, C.NAME, P.DESCRIPTION
FROM
  SALES_ORDER SO,
  CUSTOMER C,
  ITEM I,
  PRODUCT P
WHERE
  SO.CUSTOMER_ID = C.CUSTOMER_ID AND
  SO.ORDER_ID = I.ORDER_ID AND
  I.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SO.ORDER_ID;

-- 17)
SELECT COUNT(*) FROM CUSTOMER;

-- 18)
SELECT COUNT(*) FROM CUSTOMER C WHERE C.STATE = 'NY';

-- 19)
SELECT COUNT(DISTINCT MANAGER_ID) AS JEFES
FROM EMPLOYEE
WHERE MANAGER_ID IS NOT NULL;

-- 20)
SELECT * 
FROM EMPLOYEE 
ORDER BY HIRE_DATE ASC
FETCH FIRST 1 ROWS ONLY;

-- 21)
SELECT 
  E.LAST_NAME AS APELLIDO,
  E.FIRST_NAME AS NOMBRE,
  E.SALARY AS SALARIO,
  D.NAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND EXISTS (SELECT 1 FROM EMPLOYEE E1 WHERE E1.JOB_ID = E.JOB_ID AND E1.FIRST_NAME = 'JOHN' AND E1.LAST_NAME = 'SMITH')
ORDER BY SALARIO, APELLIDO;

-- 22)
SELECT 
  E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE,
  D.NAME,
  E.SALARY
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E.SALARY > (
    SELECT AVG(E1.SALARY)
    FROM EMPLOYEE E1
  );

-- 23)
SELECT *
FROM SALES_ORDER
WHERE TOTAL = (
  SELECT MIN(TOTAL)
  FROM SALES_ORDER
)
  OR TOTAL = (
    SELECT MAX(TOTAL)
    FROM SALES_ORDER
  );

-- 24)
SELECT C.NAME, COUNT(*)
FROM SALES_ORDER S, CUSTOMER C
WHERE S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.NAME;

-- 25)
SELECT C.NAME, '+' || C.AREA_CODE || ' ' || C.PHONE_NUMBER AS TELEFONO, COUNT(*)
FROM SALES_ORDER S, CUSTOMER C
WHERE S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.NAME, TELEFONO;

-- 26)
SELECT * 
FROM EMPLOYEE E
WHERE 2 <= (SELECT COUNT(*) FROM EMPLOYEE E1 WHERE E1.MANAGER_ID = E.EMPLOYEE_ID);

-- 27)
SELECT FIRST_NAME || ' ' || LAST_NAME AS NOMBRE
FROM EMPLOYEE
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEE)
OR HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM EMPLOYEE);

-- 28)
SELECT D.DEPARTMENT_ID, D.NAME AS NOMBRE_DEPTO, COUNT(E.EMPLOYEE_ID) AS CANT_EMPLEADOS
FROM DEPARTMENT D, EMPLOYEE E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.DEPARTMENT_ID IN (20, 30)
GROUP BY D.DEPARTMENT_ID, NOMBRE_DEPTO;

-- 29)
SELECT ROUND(AVG(E.SALARY), 2) AS PROMEDIO
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.NAME = 'RESEARCH';

-- 30)
SELECT D.DEPARTMENT_ID, 
  D.NAME AS NOMBRE_DEPTO, 
  ROUND(AVG(E.SALARY)) AS PROMEDIO_SALARIOS
FROM DEPARTMENT D, EMPLOYEE E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, NOMBRE_DEPTO
ORDER BY PROMEDIO_SALARIOS;

-- 31)
SELECT D.DEPARTMENT_ID, 
  D.NAME AS NOMBRE_DEPTO, 
  ROUND(AVG(E.SALARY)) AS PROMEDIO_SALARIOS
FROM DEPARTMENT D, EMPLOYEE E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, NOMBRE_DEPTO
HAVING COUNT(E.EMPLOYEE_ID) > 3
ORDER BY PROMEDIO_SALARIOS;

-- 32) 
SELECT P.PRODUCT_ID, 
  SUM(I.QUANTITY) AS UNIDADES_PEDIDAS, 
  MAX(I.TOTAL) AS TOTAL_FACTURADO
FROM PRODUCT P, ITEM I
WHERE P.PRODUCT_ID = I.PRODUCT_ID
GROUP BY P.PRODUCT_ID;

-- 33)
SELECT 
  C.NAME,
  '+' || C.AREA_CODE || ' ' || C.PHONE_NUMBER AS TELEFONO,
  COUNT(S.ORDER_ID),
  MAX(S.ORDER_DATE)
FROM CUSTOMER C, SALES_ORDER S
WHERE C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.NAME, TELEFONO;

-- 34)
SELECT L.LOCATION_ID, 
  L.REGIONAL_GROUP,
  COUNT(E.EMPLOYEE_ID) AS TOTAL_EMPLEADOS,
  SUM(E.SALARY) AS TOTAL_SALARIOS
FROM LOCATION L,
  DEPARTMENT D,
  EMPLOYEE E
WHERE L.LOCATION_ID = D.LOCATION_ID
  AND D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY L.LOCATION_ID, L.REGIONAL_GROUP
ORDER BY TOTAL_EMPLEADOS;

-- 35)
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE,
  D.NAME,
  E.SALARY,
  J.FUNCTION
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E.JOB_ID = J.JOB_ID
  AND E.SALARY > (
    SELECT E1.SALARY 
    FROM EMPLOYEE E1 
    WHERE E1.EMPLOYEE_ID = E.MANAGER_ID
  );
