-- 1)
DECLARE
  V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &INGRESE_ID_EMPLEADO;
  V_SALARY EMPLOYEE.SALARY%TYPE;
  V_COMMISSION EMPLOYEE.COMMISSION%TYPE;
  V_INCREMENTO BINARY_DOUBLE;
  E_COMISION_NULA EXCEPTION;
BEGIN
  SELECT SALARY, COMMISSION
  INTO V_SALARY, V_COMMISSION
  FROM EMPLOYEE
  WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;

  IF V_COMMISSION IS NULL THEN
    RAISE E_COMISION_NULA;
  END IF;

  CASE
    WHEN V_SALARY < 1300 THEN
      V_INCREMENTO := 1.10;
    WHEN V_SALARY BETWEEN 1300 AND 1500 THEN
      V_INCREMENTO := 1.15;
    ELSE
      V_INCREMENTO := 1.20;
  END CASE;

  UPDATE EMPLOYEE
  SET COMMISSION = COMMISSION * V_INCREMENTO
  WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;

  DBMS_OUTPUT.PUT_LINE('Comisión actualizada');

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el empleado con ID: ' || V_EMPLOYEE_ID);
  WHEN E_COMISION_NULA THEN
    DBMS_OUTPUT.PUT_LINE('El empleado no tiene comisión');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 2)
DECLARE
  TYPE TR_EMPLOYEE IS RECORD (
    EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE,
    SALARY EMPLOYEE.SALARY%TYPE,
    COMMISSION EMPLOYEE.COMMISSION%TYPE
  );
  R_EMPLOYEE TR_EMPLOYEE;
  V_CONT_NULO INTEGER := 0;
  V_CONT_10 INTEGER := 0;
  V_CONT_15 INTEGER := 0;
  V_CONT_20 INTEGER := 0;
BEGIN
  FOR R_EMPLOYEE IN (
    SELECT EMPLOYEE_ID, SALARY, COMMISSION
    FROM EMPLOYEE
  ) LOOP
    IF R_EMPLOYEE.COMMISSION IS NULL THEN
      V_CONT_NULO := V_CONT_NULO + 1;
      CONTINUE;
    END IF;

    CASE
      WHEN R_EMPLOYEE.SALARY < 1300 THEN
        UPDATE EMPLOYEE
        SET COMMISSION = COMMISSION * 1.10
        WHERE EMPLOYEE_ID = R_EMPLOYEE.EMPLOYEE_ID;
        V_CONT_10 := V_CONT_10 + 1;
      WHEN R_EMPLOYEE.SALARY BETWEEN 1300 AND 1500 THEN
        UPDATE EMPLOYEE
        SET COMMISSION = COMMISSION * 1.15
        WHERE EMPLOYEE_ID = R_EMPLOYEE.EMPLOYEE_ID;
        V_CONT_15 := V_CONT_15 + 1;
      ELSE
        UPDATE EMPLOYEE
        SET COMMISSION = COMMISSION * 1.20
        WHERE EMPLOYEE_ID = R_EMPLOYEE.EMPLOYEE_ID;
        V_CONT_20 := V_CONT_20 + 1;
    END CASE;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('Nulos: ' || V_CONT_NULO);
  DBMS_OUTPUT.PUT_LINE('10%: ' || V_CONT_10);
  DBMS_OUTPUT.PUT_LINE('15%: ' || V_CONT_15);
  DBMS_OUTPUT.PUT_LINE('20%: ' || V_CONT_20);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 3)
DECLARE
  V_JOB_ID JOB.JOB_ID%TYPE := &INGRESE_JOB_ID;
  E_NOT_FOUND EXCEPTION;
  E_FK EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_FK, -02292);
BEGIN
  DELETE FROM JOB
  WHERE JOB_ID = V_JOB_ID;

  IF SQL%NOTFOUND THEN
    RAISE E_NOT_FOUND;
  END IF;

EXCEPTION
  WHEN E_NOT_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el Job con ID: ' || V_JOB_ID);
  WHEN E_FK THEN
    DBMS_OUTPUT.PUT_LINE('No se puede eliminar el Job con ID ' || V_JOB_ID || ' ya que hay empleados asignados al mismo.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 4)
DECLARE
  V_JOB_ID JOB.JOB_ID%TYPE;
  V_FUNCTION JOB.FUNCTION%TYPE := '&INGRESE_FUNCION';
BEGIN
  SELECT MAX(JOB_ID) + 1
  INTO V_JOB_ID
  FROM JOB;

  DBMS_OUTPUT.PUT_LINE('Insertando a JOB con ID ' || V_JOB_ID);

  INSERT INTO JOB (JOB_ID, FUNCTION)
  VALUES (V_JOB_ID, V_FUNCTION);
  COMMIT;
END;

-- 5)
DECLARE
  V_PRODUCT_ID PRODUCT.PRODUCT_ID%TYPE := &INGRESE_PRODUCT_ID;
  V_PORCENTAJE INTEGER;
  TYPE TR_PRICE IS RECORD (
    PRODUCT_ID PRICE.PRODUCT_ID%TYPE,
    LIST_PRICE PRICE.LIST_PRICE%TYPE,
    MIN_PRICE PRICE.MIN_PRICE%TYPE,
    START_DATE PRICE.START_DATE%TYPE,
    VENTAS INTEGER
  );
  R_PRICE TR_PRICE;
BEGIN
  SELECT P.PRODUCT_ID, P.LIST_PRICE, P.MIN_PRICE, P.START_DATE, COUNT(I.ORDER_ID)
  INTO R_PRICE
  FROM PRICE P 
  LEFT OUTER JOIN ITEM I 
    ON P.PRODUCT_ID = I.PRODUCT_ID
  WHERE P.PRODUCT_ID = V_PRODUCT_ID AND
    P.END_DATE IS NULL
  GROUP BY P.PRODUCT_ID, P.LIST_PRICE, P.MIN_PRICE, P.START_DATE;

  CASE
    WHEN R_PRICE.VENTAS <= 2 THEN
      V_PORCENTAJE := 90;
    WHEN R_PRICE.VENTAS > 2 THEN
      V_PORCENTAJE := 80;
    ELSE
      V_PORCENTAJE := 50;
  END CASE;

  DBMS_OUTPUT.PUT_LINE('Reduciendo precio del producto con ID ' || V_PRODUCT_ID || ' al ' || V_PORCENTAJE || '%');

  UPDATE PRICE
  SET END_DATE = SYSDATE()
  WHERE PRODUCT_ID = R_PRICE.PRODUCT_ID
  AND END_DATE IS NULL;

  INSERT INTO PRICE (PRODUCT_ID, LIST_PRICE, MIN_PRICE, START_DATE, END_DATE)
  VALUES (
    R_PRICE.PRODUCT_ID, 
    (R_PRICE.LIST_PRICE * V_PORCENTAJE) / 100,
    (R_PRICE.MIN_PRICE * V_PORCENTAJE) / 100,
    SYSDATE(),
    NULL
  );
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el producto con ID:' || V_PRODUCT_ID);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

-- 6)
DECLARE
  V_ID_CLIENTE CUSTOMER.CUSTOMER_ID%TYPE := &INGRESE_SU_ID;
  V_CANT_ORDENES INTEGER := 0;
  V_CUSTOMER_NAME CUSTOMER.NAME%TYPE;
BEGIN
  SELECT COUNT(ORDER_ID)
  INTO V_CANT_ORDENES
  FROM SALES_ORDER
  WHERE CUSTOMER_ID = V_ID_CLIENTE;

  SELECT NAME
  INTO V_CUSTOMER_NAME
  FROM CUSTOMER
  WHERE CUSTOMER_ID = V_ID_CLIENTE;

  CASE 
    WHEN V_CANT_ORDENES BETWEEN 1 AND 3 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES REGULAR');
    WHEN V_CANT_ORDENES BETWEEN 4 AND 6 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES BUENO');
    WHEN V_CANT_ORDENES > 6 THEN
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' ES MUY BUENO');
    ELSE
      DBMS_OUTPUT.PUT_LINE('El cliente ' || V_CUSTOMER_NAME || ' no tiene órdenes a su nombre');
  END CASE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró el cliente');
END;
