-- 8)
DECLARE
  CURSOR C_CURSOR IS
    SELECT S.ORDER_ID, S.ORDER_DATE, I.PRODUCT_ID
    FROM SALES_ORDER S, ITEM I
    WHERE S.ORDER_ID = I.ORDER_ID;
BEGIN
  FOR REC IN C_CURSOR LOOP
    DBMS_OUTPUT.PUT_LINE('ORDER_ID: ' || REC.ORDER_ID || ', DATE: ' || REC.ORDER_DATE || ', PRODUCT_ID: ' || REC.PRODUCT_ID);
  END LOOP;
END;

-- 9)
DECLARE
  V_CUSTOMER_ID CUSTOMER.CUSTOMER_ID%TYPE := &INGRESE_CUSTOMER_ID;
  V_CONT INTEGER := 0;
  CURSOR C_ORDEN IS
    SELECT S.ORDER_ID, S.ORDER_DATE, P.DESCRIPTION
    FROM SALES_ORDER S, ITEM I, PRODUCT P
    WHERE S.CUSTOMER_ID = V_CUSTOMER_ID
      AND S.ORDER_ID = I.ORDER_ID
      AND I.PRODUCT_ID = P.PRODUCT_ID;
BEGIN
  FOR REC IN C_ORDEN LOOP
    V_CONT := V_CONT + 1;
    DBMS_OUTPUT.PUT_LINE('ORDER_ID: ' || REC.ORDER_ID || ', DATE: ' || REC.ORDER_DATE || ', DESCR: ' || REC.DESCRIPTION);
  END LOOP;

  IF V_CONT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('No se encontraron registros');
  END IF;
END;

-- 10)
DECLARE
  V_DEPTO_ID DEPARTMENT.DEPARTMENT_ID%TYPE := &INGRESE_ID;
  V_CONT INTEGER := 0;
  CURSOR C_DEPTOS IS
    SELECT E.LAST_NAME, E.FIRST_NAME, E.SALARY
    FROM EMPLOYEE E, JOB J
    WHERE E.DEPARTMENT_ID = V_DEPTO_ID
    AND E.JOB_ID = J.JOB_ID
    AND J.FUNCTION = 'CLERK'
    ORDER BY E.LAST_NAME;
  E_NO_CLERKS EXCEPTION;
BEGIN
  FOR REC IN C_DEPTOS LOOP
    V_CONT := V_CONT + 1;
    CASE
      WHEN REC.SALARY < 1000 THEN
        DBMS_OUTPUT.PUT_LINE(REC.LAST_NAME || ', ' || REC.FIRST_NAME || ' es candidato a aumento');
      ELSE
        DBMS_OUTPUT.PUT_LINE(REC.LAST_NAME || ', ' || REC.FIRST_NAME || ' no es candidato a aumento');
    END CASE;
  END LOOP;

  IF V_CONT = 0 THEN
    RAISE E_NO_CLERKS;
  END IF;
EXCEPTION
  WHEN E_NO_CLERKS THEN
    DBMS_OUTPUT.PUT_LINE('El departamento ' || V_DEPTO_ID || ' no tiene candidatos a aumento de salario.');
END;

-- 11)
SELECT P1.DESCRIPTION, P2.LIST_PRICE
FROM PRODUCT P1, PRICE P2
WHERE P1.PRODUCT_ID = P2.PRODUCT_ID
AND P2.END_DATE IS NULL
ORDER BY P2.LIST_PRICE DESC
FETCH FIRST 5 ROWS ONLY;

-- 12)
DECLARE
  CURSOR C_DEPTOS IS
    SELECT D.DEPARTMENT_ID, D.NAME, L.REGIONAL_GROUP
    FROM DEPARTMENT D, LOCATION L
    WHERE D.LOCATION_ID = L.LOCATION_ID
    ORDER BY DEPARTMENT_ID;
  CURSOR C_EMPLEADOS (P_DEP_ID DEPARTMENT.DEPARTMENT_ID%TYPE) IS
    SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
    FROM EMPLOYEE
    WHERE DEPARTMENT_ID = P_DEP_ID
    ORDER BY LAST_NAME, FIRST_NAME;
BEGIN
  FOR DEPTO IN C_DEPTOS LOOP
    DBMS_OUTPUT.PUT_LINE(DEPTO.DEPARTMENT_ID || ' - ' || DEPTO.NAME || ' - ' || DEPTO.REGIONAL_GROUP);
    DBMS_OUTPUT.PUT_LINE('------------------------------');
    FOR EMPL IN C_EMPLEADOS(DEPTO.DEPARTMENT_ID) LOOP
      DBMS_OUTPUT.PUT_LINE(EMPL.LAST_NAME || ', ' || EMPL.FIRST_NAME || '     ' || EMPL.HIRE_DATE);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('');
  END LOOP;
END;
