CREATE OR REPLACE
PACKAGE BODY PA_EMPLEADOS AS

  PROCEDURE PR_CONSULTA_NOMBRE
    (PI_EMP_ID EMPLOYEE.EMPLOYEE_ID%TYPE) AS
    V_EMP_NOMBRE EMPLOYEE.FIRST_NAME%TYPE;
    V_EMP_APELLIDO EMPLOYEE.LAST_NAME%TYPE;
  BEGIN
    SELECT FIRST_NAME, LAST_NAME
    INTO V_EMP_NOMBRE, V_EMP_APELLIDO
    FROM EMPLOYEE
    WHERE EMPLOYEE_ID = PI_EMP_ID;

    DBMS_OUTPUT.PUT_LINE(V_EMP_NOMBRE || ' ' || V_EMP_APELLIDO);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('No existe el empleado');
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
  END PR_CONSULTA_NOMBRE;

  PROCEDURE PR_LISTA_EMP 
    (PI_DEP_ID DEPARTMENT.DEPARTMENT_ID%TYPE) AS
  BEGIN
    NULL;
  END PR_LISTA_EMP;

END PA_EMPLEADOS;