-- U1-E22
DECLARE
  -- Variables
  v_first_name EMPLOYEE.FIRST_NAME%TYPE;
  v_last_name EMPLOYEE.LAST_NAME%TYPE;
  v_new_salary EMPLOYEE.SALARY%TYPE;
  v_manager_id EMPLOYEE.MANAGER_ID%TYPE;
  v_manager_salary EMPLOYEE.SALARY%TYPE;
  -- Excepciones
  e_no_manager EXCEPTION;
  e_salary_too_high EXCEPTION;
  e_salary_too_large EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_salary_too_large, -6502);
BEGIN
  v_first_name := '&INGRESE_NOMBRE';
  v_last_name := '&INGRESE_APELLIDO';
  v_new_salary := '&INGRESE_NUEVO_SUELDO';

  -- Obtener manager ID
  SELECT MANAGER_ID
  INTO v_manager_id
  FROM EMPLOYEE
  WHERE FIRST_NAME = v_first_name
    AND LAST_NAME = v_last_name;
  
  -- Validar si no tiene Jefe
  IF v_manager_id IS NULL THEN
    RAISE e_no_manager;
  END IF;

  -- Obtener salario del Jefe
  SELECT SALARY
  INTO v_manager_salary
  FROM EMPLOYEE
  WHERE EMPLOYEE_ID = v_manager_id;

  -- Validar que el salario nuevo no supere
  -- al del Jefe
  IF v_manager_salary < v_new_salary THEN
    RAISE e_salary_too_high;
  END IF;

  -- Actualizar salario del empleado
  UPDATE EMPLOYEE
  SET SALARY = V_NEW_SALARY
  WHERE FIRST_NAME = v_first_name
    AND LAST_NAME = v_last_name;
  
  -- Informar resultado exitoso
  DBMS_OUTPUT.PUT_LINE('Salario actualizado correctamente.');
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró al empleado.');
  WHEN e_no_manager THEN
    DBMS_OUTPUT.PUT_LINE('El empleado no tiene jefe.');
  WHEN e_salary_too_high THEN
    DBMS_OUTPUT.PUT_LINE('El nuevo salario del empleado supera al de su jefe.');
  WHEN e_salary_too_large THEN
    DBMS_OUTPUT.PUT_LINE('El salario es demasiado grande.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;

CREATE OR REPLACE PROCEDURE PR_SUMA
(
  PI_NUM1 IN NUMBER,
  PI_NUM2 IN NUMBER,
  PO_TOTAL OUT NUMBER
) AS
BEGIN
  PO_TOTAL := PI_NUM1 + PI_NUM2;
END PR_SUMA;

DECLARE
  V_TOT NUMBER;
BEGIN
  PR_SUMA(1, 5, V_TOT);
  DBMS_OUTPUT.PUT_LINE('Total: ' || V_TOT);
END;

CREATE OR REPLACE PROCEDURE PR_MULTIPLICA
(
  PI_NUM1 IN NUMBER,
  PI_NUM2 IN NUMBER DEFAULT 2
) AS
  V_RESULT NUMBER;
BEGIN
  V_RESULT := PI_NUM1 * PI_NUM2;
  DBMS_OUTPUT.PUT_LINE('Resultado: ' || V_RESULT);
END PR_MULTIPLICA;

CREATE OR REPLACE PROCEDURE PR_LISTA_DEP
(
  PI_DEP_ID IN DEPARTMENT.DEPARTMENT_ID%TYPE DEFAULT 10
) AS
  V_NOMBRE DEPARTMENT.NAME%TYPE;
  V_REGION LOCATION.REGIONAL_GROUP%TYPE;
BEGIN
  SELECT NAME, REGIONAL_GROUP
  INTO V_NOMBRE, V_REGION
  FROM DEPARTMENT D, LOCATION L
  WHERE L.LOCATION_ID = D.LOCATION_ID
  AND D.DEPARTMENT_ID = PI_DEP_ID;

  DBMS_OUTPUT.PUT_LINE(V_NOMBRE || ' ' || V_REGION);
END PR_LISTA_DEP;

CREATE OR REPLACE PROCEDURE PR_CURSOR
(
  PI_DEP_ID IN DEPARTMENT.DEPARTMENT_ID%TYPE DEFAULT 10
) AS
  CURSOR C_EMPLEADO IS
    SELECT FIRST_NAME, LAST_NAME
    FROM EMPLOYEE
    WHERE DEPARTMENT_ID = PI_DEP_ID;
  R_EMPLEADO C_EMPLEADO%ROWTYPE;
BEGIN
  OPEN C_EMPLEADO;
  WHILE C_EMPLEADO%FOUND LOOP
    FETCH C_EMPLEADO INTO R_EMPLEADO;
    DBMS_OUTPUT.PUT_LINE(R_EMPLEADO.FIRST_NAME || ' ' ||R_EMPLEADO.LAST_NAME);
  END LOOP;
  CLOSE C_EMPLEADO;
END;

CREATE OR REPLACE FUNCTION FU_NOMBRE
  RETURN NULL AS
BEGIN
  NULL;
END FU_NOMBRE;
