CREATE OR REPLACE FUNCTION FU_EMP_ID (
  PI_NOMBRE IN EMPLOYEE.FIRST_NAME%TYPE,
  PI_APELLIDO IN EMPLOYEE.LAST_NAME%TYPE
)
RETURN EMPLOYEE.EMPLOYEE_ID%TYPE AS
  V_EMP_ID EMPLOYEE.EMPLOYEE_ID%TYPE;
BEGIN
  SELECT EMPLOYEE_ID
  INTO V_EMP_ID
  FROM EMPLOYEE
  WHERE FIRST_NAME = PI_NOMBRE
  AND LAST_NAME = PI_APELLIDO;
  RETURN V_EMP_ID;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20001, 'No existe el empleado');
  WHEN TOO_MANY_ROWS THEN
    RAISE_APPLICATION_ERROR(-20002, 'Existe mas de un empleado');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003, 'Error inesperado: ' || SQLERRM);
END FU_EMP_ID;

CREATE OR REPLACE PROCEDURE PR_BORRAR_CLIENTES (
  PI_NOMBRE IN EMPLOYEE.FIRST_NAME%TYPE,
  PI_APELLIDO IN EMPLOYEE.LAST_NAME%TYPE
) AS
BEGIN
  DELETE
  FROM CUSTOMER
  WHERE SALESPERSON_ID = FU_EMP_ID(PI_NOMBRE, PI_APELLIDO); -- puede tirar error si el cliente tiene orders

  DBMS_OUTPUT.PUT_LINE('Se borraron' || SQL%ROWCOUNT || ' clientes');
END;