-- SET SERVEROUTPUT ON;

DECLARE
  V_NOMBRE VARCHAR2(50);
  V_EDAD NUMBER(2);
  V_FECHA DATE;
  C_IVA CONSTANT NUMBER(3,2) := 0.21;
  V_PRECIO NUMBER(6,2);
BEGIN
  V_NOMBRE := 'Juan';
  V_EDAD := &INGRESE_SU_EDAD;
  DBMS_OUTPUT.PUT_LINE('Nombre: ' || V_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Edad: ' || V_EDAD);
  V_FECHA := TO_DATE('20122026', 'DDMMYYYY');
  DBMS_OUTPUT.PUT_LINE('Fecha: ' || V_FECHA);
  V_PRECIO := 100;
  DBMS_OUTPUT.PUT_LINE('Precio: ' || V_PRECIO);
END;

DECLARE
  V_NOMBRE VARCHAR2(50);
  V_EDAD NUMBER(2);
  V_MENSAJE VARCHAR2(50);
BEGIN
  V_NOMBRE := '&INGRESE_SU_NOMBRE';
  V_EDAD := &INGRESE_SU_EDAD;
  IF V_EDAD BETWEEN 1 AND 5 THEN
    V_MENSAJE := 'Bebe';
  ELSIF V_EDAD BETWEEN 6 AND 12 THEN
    V_MENSAJE := 'Niño';
  ELSIF V_EDAD BETWEEN 13 AND 18 THEN
    V_MENSAJE := 'Adolescente';
  ELSIF V_EDAD BETWEEN 19 AND 25 THEN
    V_MENSAJE := 'Joven';
  ELSIF V_EDAD BETWEEN 26 AND 45 THEN
    V_MENSAJE := 'Adulto';
  ELSIF V_EDAD > 45 THEN
    V_MENSAJE := 'Nuevo Adulto';
  END IF;

  DBMS_OUTPUT.PUT_LINE('Nombre: ' || V_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Edad: ' || V_EDAD);
  DBMS_OUTPUT.PUT_LINE('Mensaje: ' || V_MENSAJE);
END;


DECLARE
  V_EMPLEADO_ID EMPLOYEE.EMPLOYEE_ID%TYPE;
  V_SUELDO EMPLOYEE.SALARY%TYPE;
BEGIN
  V_EMPLEADO_ID := &INGRESE_SU_ID;

  SELECT E.SALARY
  INTO V_SUELDO
  FROM EMPLOYEE E
  WHERE E.EMPLOYEE_ID = V_EMPLEADO_ID;

  IF V_SUELDO < 1300 THEN
    DBMS_OUTPUT.PUT_LINE('Sueldo bajo');
  ELSIF V_SUELDO BETWEEN 1300 AND 1500 THEN
    DBMS_OUTPUT.PUT_LINE('Sueldo medio');
  ELSIF V_SUELDO > 1500 THEN
    DBMS_OUTPUT.PUT_LINE('Sueldo alto');
  END IF;
END;
