-- Incrementar un 25% el precio de artículos de los rubros de herramientas
UPDATE ARTICULO
SET PRECIO = PRECIO * 1.25
WHERE RUBRO IN (SELECT R.COD_RUBRO
                FROM RUBRO AS R
                WHERE LOWER(R.DESCRIPCION) LIKE LOWER('herramientas%'));

SELECT AR.NROARTIC, AR.PRECIO, RU.DESCRIPCION
FROM ARTICULO AS AR
  INNER JOIN RUBRO AS RU ON AR.RUBRO = RU.COD_RUBRO
WHERE LOWER(RU.DESCRIPCION) LIKE LOWER('herramientas%');

-- Ingresar un nuevo rubro con código 15 y descripción "Escaleras"
INSERT INTO RUBRO (COD_RUBRO, DESCRIPCION)
  VALUES (15, 'Escaleras');

SELECT * FROM RUBRO;

-- Sumar 5 unidades a la cantidad comprada del artículo con código 4040
-- en el renglón 7 de la factura nro. 1005.
UPDATE DETALLE
SET CANTIDAD = CANTIDAD + 5
WHERE NROFACTURA = 1005
AND RENGLON = 7
AND ARTICULO = 4040;

SELECT * FROM DETALLE
WHERE NROFACTURA = 1005
AND RENGLON = 7
AND ARTICULO = 4040;

-- Dar de baja a los artículos que nunca se vendieron.
DELETE FROM ARTICULO
WHERE NROARTIC NOT IN (SELECT DISTINCT ARTICULO FROM DETALLE);

SELECT NROARTIC, DESCRIPCION
FROM ARTICULO
WHERE NROARTIC NOT IN (SELECT DISTINCT ARTICULO FROM DETALLE);
